version: 2.1
executors:
  go:
    docker:
      - image: circleci/golang:1.12
    environment:
      GO111MODULES: on
      TEST_RESULTS: /tmp/test-results

jobs:
  build:
    executor: go
    steps:
      - checkout
      - run: mkdir -p ${TEST_RESULTS}
      - run: go get github.com/jstemmer/go-junit-report
      - run:
          name: Build echo service for tests
          command: make build/echo
      - run:
          name: Unit Tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make ci-test | tee ${TEST_RESULTS}/go-test.out
      - run:
          name: Build ladle command
          command: make build/ladle

      - store_artifacts:
          path: /tmp/test-results
          destination: test-output
      - store_artifacts:
          path: build
          destination: build
      - store_test_results:
          path: /tmp/test-results



